### ISSUE TITLE
请教err_test.go中的TestCatch2和TestCatch3是针对什么情况的测试？

### ISSUE THREAD

**Issue by aQuaYi** [reusee/codes#1]
``` go
func TestCatch2(t *testing.T) {
    e := func() (err error) {
        defer ct(&err)
        return
    }()
    if e != nil {
        t.Fail()
    }
}
```

``` go
func TestCatch3(t *testing.T) {
    e := func() (err error) {
        defer ct(&err)
        return errors.New("Err")
    }()
    if e == nil || e.Error() != "Err" {
        t.Fail()
    }
}
```

为了避免歧义，我把部分err改成了e

在我看来，上面两个测试中的ct(&err) 都只执行了ct函数的第一行。因为没有panic()，所以
···go
if p := recover(); p != nil { //p==nil
}
···
不会执行if内的语句。也就是说，在TestCatch后，TestCatch2和TestCatch3并没有增加测试代码的覆盖率。所以，我很好奇TestCatch2和TestCatch3的作用。

**Comment by reusee** [comment]
TestCatch2测试的是，没有错误时，返回nil；
TestCatch3测试的是，直接用return返回错误，不通过panic，能正确返回该err。
这两个都是实际中经常会出现的情况。
不是说没有增加覆盖率的就不需要测，也不是说覆盖率100%了就覆盖了所有情况了。按行做覆盖率测试其实还是很粗糙的方法。实际可能出现什么情况就要测什么情况，覆盖率只是一种参考。

**Comment by aQuaYi** [comment]
非常感谢你的回复。
你说的很对，确实不应该简单的按照覆盖率来判断测试文件的好坏。ct()里面是if下面还有if和else，确实是要测试3种情况。
